### ISSUE TITLE
Possibilidade de criar threads nos tópicos.

### ISSUE THREAD

**Issue by KingBrel** [Paulo-Bezerra/forum#4]
Estou analisando a possibilidade de limitar o numero de caracteres, do conteúdo do tópico, para 500 caracteres.
Sendo assim em casos que seja necessário usar mais de 500 caracteres, o usuário pode criar uma _thread_ igual ao Twitter. A implementação dela será semelhante à implementação de um comentário, porém a sua função será de continuação do assunto do tópico, feita pelo autor do mesmo.

**Comment by Paulo-Bezerra** [comment]
achei inconveniente a criação desse issue, você poderia abordar esse assunto nos que já foram criados. Se concorda comigo, delete-o, por favor!

**Comment by b-andersonlucas** [comment]
> achei inconveniente a criação desse issue, você poderia abordar esse assunto nos que já foram criados. Se concorda comigo, delete-o, por favor!

Talvez pudesse abordar neste tópico #1  . Pois está relacionado ao funcionamento de um dos requisitos - RF - 01


> Estou analisando a possibilidade de limitar o numero de caracteres, do conteúdo do tópico, para 500 caracteres.
> Sendo assim em casos que seja necessário usar mais de 500 caracteres, o usuário pode criar uma _thread_ igual ao Twitter. A implementação dela será semelhante à implementação de um comentário, porém a sua função será de continuação do assunto do tópico, feita pelo autor do mesmo.

Mas respondendo a sua sugestão... olhando do ponto de vista da usabilidade não acho necessário limitar a quantidade de caracteres do conteúdo do tópico, pois o conceito de um fórum é diferente.

**Comment by Paulo-Bezerra** [comment]
Concordo com tudo abordado por [Anderson](@b-andersonlucas )!

**Comment by DicksonSilva** [comment]
Acho interessante a ideia, mas por enquanto sugiro que façamos algo mais simples. A necessidade de respostas com mais de 700 caracteres (número que está definido modelo relacional deste projeto) pode ser "resolvida" no próprio campo de resposta. Podemos adotar no requisito: "**RF 03**" a possibilidade de criar respostas aninhadas, em que uma ou mais respostas podem estar direcionadas a um determinado tópico/comentário. Então, se um dos participantes da discussão deseja dar uma resposta maior, além do número de caracteres disponível, ele irá responder mais de uma vez, mas suas respostas estarão aninhadas (**uma abaixo da outra, para respostas mais longas e uma dentro da outra, quando houver respostas de comentários**) possibilitando assim umas resposta "mais completa" atendendo a sua necessidade. O que acham?

**Comment by Paulo-Bezerra** [comment]
Bem pontuado, (Dickson)[@DicksonSilva ]! Acho que isso seria bem organizado e direcionado ao requisito indicado por você.
